In [3]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior_new.csv')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Term           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code              3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [5]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Term,Discount Applied,Promo Code,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,2,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Express,No,Yes,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,3899,2223,3827,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Term             0
Discount Applied          0
Promo Code                0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
df['Review_Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Term             0
Discount Applied          0
Promo Code                0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
Review_Rating             0
dtype: int64

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount(usd)':'purchase_amount'})

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_term_',
       'discount_applied', 'promo_code', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'review_rating'],
      dtype='str')

In [11]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4 , labels = labels)

In [12]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [13]:
# crete column purchase_frequency_days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quaterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                      NaN              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                      NaN              Quarterly

In [15]:
df[['discount_applied','promo_code']].head(10)

  discount_applied promo_code
0              Yes        Yes
1              Yes        Yes
2              Yes        Yes
3              Yes        Yes
4              Yes        Yes
5              Yes        Yes
6              Yes        Yes
7              Yes        Yes
8              Yes        Yes
9              Yes        Yes

In [16]:
(df['discount_applied'] == df['promo_code']).all()

np.False_

In [17]:
df = df.drop('promo_code', axis=1)

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_term_',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'review_rating', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [19]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.1.4)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\HP\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [27]:
from sqlalchemy import create_engine
username = "postgres"
password = "Owais"
host = "localhost"
port = "5432"
database = "customer_behaviour"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table'{table_name}' in database '{database}'.")

Data successfully loaded into table'customer' in database 'customer_behaviour'.

In [26]:
df = df.loc[:, ~df.columns.duplicated()]

In [28]:
!pip install pymsql sqlalchemy

Collecting pymsql
  Downloading pymsql-0.0.1-py3-none-any.whl.metadata (232 bytes)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.1.4)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.16.0)
Downloading pymsql-0.0.1-py3-none-any.whl (1.3 kB)
Installing collected packages: pymsql
Successfully installed pymsql-0.0.1

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\HP\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [33]:
!pip install PyMySQL

Collecting PyMySQL
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: PyMySQL
Successfully installed PyMySQL-1.2.3

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\HP\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [42]:
from sqlalchemy import create_engine

username = "root"
password = ""
host = "localhost"
port = "3306"
database = "mydatabase"

# 'pymsysql' ko theek karke 'pymysql' kar diya gaya hai
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = "mytable"
df.to_sql(table_name, engine, if_exists="replace", index=False)

pd.read_sql("SELECT * FROM mytable LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_term_,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,free shipping,Yes,14,Venmo,Fortnightly,Middle-aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Express,Yes,23,Credit Card,Weekly,Middle-aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Express,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Express,Yes,31,PayPal,Annually,Middle-aged,365.0

In [1]:
!pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.1.4)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\HP\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [44]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus